// This file is auto-generated by TanStack Router
// Do not edit manually

import { Route as rootRoute } from './routes/__root'
import { Route as TasksRoute } from './routes/tasks'
import { Route as RepositoriesRoute } from './routes/repositories'
import { Route as MetricsRoute } from './routes/metrics'
import { Route as IndexRoute } from './routes/index'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/metrics': {
      preLoaderRoute: typeof MetricsRoute
      parentRoute: typeof rootRoute
    }
    '/repositories': {
      preLoaderRoute: typeof RepositoriesRoute
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      preLoaderRoute: typeof TasksRoute
      parentRoute: typeof rootRoute
    }
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  MetricsRoute,
  RepositoriesRoute,
  TasksRoute,
])
